name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16 

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make
