name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16 

    - name: Install ROOT dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev
        wget https://root.cern/download/root_v6.34.04.Linux-ubuntu20.04-x86_64-gcc9.4.tar.gz
        tar -xzf root_v6.34.04.Linux-ubuntu20.04-x86_64-gcc9.4.tar.gz
        echo "source $PWD/root/bin/thisroot.sh" >> $GITHUB_ENV
        source $PWD/root/bin/thisroot.sh

    - name: Build project
      run: |
        source $GITHUB_ENV
        mkdir build && cd build
        cmake ..
        make

    - name: Run executable
      run: |
        source $GITHUB_ENV
        ./build/main
