name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.16

    - name: Install dependencies and Apptainer manually
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libseccomp-dev \
          pkg-config \
          squashfs-tools \
          cryptsetup \
          curl \
          fuse \
          libfuse-dev \
          git \
          uuid-dev \
          cmake

        export VERSION=1.2.5
        wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
        sudo dpkg -i apptainer_${VERSION}_amd64.deb

    - name: Install eic-shell
      run: |
        curl -L https://github.com/eic/eic-shell/raw/main/install.sh | bash

    - name: Build inside eic-shell
      run: |
        ./eic-shell <<'EOF'
        make all
        EOF

    - name: Run inside eic-shell
      run: |
        ./eic-shell <<'EOF'
        make run
        EOF

    - name: Upload histogram artifact
      uses: actions/upload-artifact@v4
      with:
        name: hist-output
        path: hist.png
