name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16 

    - name: Install ROOT w/ dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev
        wget https://root.cern/download/root_v6.34.04.Linux-ubuntu20.04-x86_64-gcc9.4.tar.gz
        tar -xzf root_v6.34.04.Linux-ubuntu20.04-x86_64-gcc9.4.tar.gz

    - name: Build project
      run: |
        source root/bin/thisroot.sh
        make all

    - name: Run project
      run: |
        source root/bin/thisroot.sh
        make run

    - name: Upload histogram
      uses: actions/upload-artifact@v4
      with:
        name: hist-output
        path: hist.png
