name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16 

    - name: Install dependencies and eic-shell
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev wget singularity-container
        curl -L https://github.com/eic/eic-shell/raw/main/install.sh | bash

    - name: Build project inside eic-shell
      run: |
        ./eic-shell << 'EOF'
        make all
        EOF

    - name: Run project inside eic-shell
      run: |
        ./eic-shell << 'EOF'
        make run
        EOF

    - name: Upload histogram artifact
      uses: actions/upload-artifact@v4
      with:
        name: hist-output
        path: hist.png
