name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Set up Python 3.10.16 
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.16

    - name: Install dependencies and Apptainer manually
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libseccomp-dev \
          pkg-config \
          squashfs-tools \
          squashfuse \
          fuse2fs \
          fuse3 \
          fuse-overlayfs \
          cryptsetup \
          curl \
          libfuse-dev \
          git \
          uuid-dev \
          cmake

        export VERSION=1.2.5
        wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
        sudo dpkg -i apptainer_${VERSION}_amd64.deb

    - name: Install eic-shell
      run: |
        curl -L https://github.com/eic/eic-shell/raw/main/install.sh | bash

    - name: Build inside eic-shell
      run: |
        ./eic-shell <<'EOF'
        make all
        EOF

    - name: Run test00_readData
      run: |
        ./eic-shell <<'EOF'
        make test00_readData
        EOF

    - name: Run test01_grabFiles
      run: |
        ./eic-shell <<'EOF'
        make test01_grabFiles
        EOF

    - name: Run test02_dataSummary
      run: |
        ./eic-shell <<'EOF'
        make test02_dataSummary
        EOF

    - name: Run test03_weightHistDIS
      run: |
        ./eic-shell <<'EOF'
        make test03_weightHistDIS
        EOF

    - name: Run test04_printEvent
      run: |
        ./eic-shell <<'EOF'
        make test04_printEvent
        EOF

    - name: Run test05_weightHistSIDIS
      run: |
        ./eic-shell <<'EOF'
        make test05_weightHistSIDIS
        EOF

    - name: Run test06_uploadCSV
      run: |
        ./eic-shell <<'EOF'
        make test06_uploadCSV
        EOF

    - name: Run test07_migrationReader
      run: |
        ./eic-shell <<'EOF'
        make test07_migrationReader
        EOF

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/

